import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.brighterlawsuite-staging.co.uk/Account/LogOn');
  await page.getByLabel('Username').click();
  await page.goto('https://www.brighterlawsuite-staging.co.uk/Account/LogOn');
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('TurnerUser');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Test1234');
  await page.goto('https://www.brighterlawsuite-staging.co.uk/');
  await page.getByRole('link', { name: ' Add New Client' }).click();
  await page.locator('a').filter({ hasText: 'Select Team' }).click();
  await page.locator('#introducerTeamId_chosen').getByRole('textbox').fill('li');
  await page.locator('#introducerTeamId_chosen').getByText('Lindsey Williams').click();
  await page.getByText('Purchase', { exact: true }).first().click();
  await page.getByLabel('Purchase Postcode').click();
  await page.getByLabel('Purchase Postcode').click();
  await page.getByLabel('Purchase Postcode').fill('RG30 3NG');
  await page.getByText('Find Local Authority').click();
  await page.getByLabel('Purchase Price').click();
  await page.getByLabel('Purchase Price').fill('120');
  await page.locator('a').filter({ hasText: 'Select Title' }).click();
  await page.locator('#titleId_chosen').getByText('Mrs', { exact: true }).click();
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('Rathna');
  await page.getByLabel('First Name').press('Tab');
  await page.getByLabel('Last Name').fill('Karlapudi');
  await page.getByLabel('Last Name').press('Tab');
  await page.getByLabel('Email Address').fill('rathnamani.karlapudi@dyedurham.com');
  await page.getByLabel('Phone Number').click();
  await page.getByLabel('Phone Number').fill('441234567890');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.goto('https://www.brighterlawsuite-staging.co.uk/Cases/Create#/estimate/11eabe99-3705-415c-8850-22471c8ec3f7');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#details div').filter({ hasText: 'Client Details Service Address Line 1 is required. Company Title MrMrsMissMsMxMr' }).getByPlaceholder('Start typing a postcode or address').click();
  await page.locator('#details div').filter({ hasText: 'Client Details Service Address Line 1 is required. Company Title MrMrsMissMsMxMr' }).getByPlaceholder('Start typing a postcode or address').click();
  await page.locator('#details div').filter({ hasText: 'Client Details Service Address Line 1 is required. Company Title MrMrsMissMsMxMr' }).getByPlaceholder('Start typing a postcode or address').fill('RG30 3NG');
  await page.getByText('1 Ainsdale Crescent Reading, RG30 3NG', { exact: true }).click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(1).click();
  await page.locator('#details div').filter({ hasText: 'Client Details Service Address Line 1 is required. Company Title MrMrsMissMsMxMr' }).getByPlaceholder('Start typing a postcode or address').click();
  await page.locator('#details div').filter({ hasText: 'Client Details Service Address Line 1 is required. Company Title MrMrsMissMsMxMr' }).getByPlaceholder('Start typing a postcode or address').fill('RG30 1AA ');
  await page.getByText('192 Oxford Road Reading, RG30 1AA').click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(1).click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(1).click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(1).fill('RG30 3NG');
  await page.getByText('1 Ainsdale Crescent Reading, RG30 3NG', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Order ' }).click();
  const page1 = await page1Promise;
  await page1.locator('a').filter({ hasText: 'SELECT COMPANY' }).click();
  await page1.locator('#companySelect_chosen').getByText('Turner and Turner').click();
  await page1.locator('#teams_chosen').getByRole('textbox').fill('li');
  await page1.locator('#teams_chosen').getByText('Lindsey Williams').click();
  await page1.goto('https://staging.spidercubed-staging.co.uk/Orders/Create/1522350');
  await page1.goto('https://staging.spidercubed-staging.co.uk/Orders/Create/1522350#/address');
  await page1.getByRole('button', { name: '1 Ainsdale Crescent, READING, Berkshire, RG30 3NG', exact: true }).click();
  await page1.getByRole('button', { name: 'Next ' }).click();
  await page1.locator('.clearfix > a:nth-child(2)').first().click();
  await page1.getByText('Proceed With Order').click();
  await page1.getByText('Funds To Collect').click();
  await page1.locator('#customer_firstname').click();
  await page1.locator('#customer_firstname').press('Control+r');
  await page1.locator('#customer_firstname').fill('Rathna');
  await page1.locator('#customer_lastname').click();
  await page1.locator('#customer_lastname').fill('karlapudi');
  await page1.locator('#customer_homephone').click();
  await page1.locator('#customer_homephone').fill('1234567891');
  await page1.locator('#customer_email').click();
  await page1.locator('#customer_email').fill('rathnamani.karlapudi@dyedurham.com');
  await page1.getByLabel('Use Order Address').check();
  await page1.getByText('Our Reference', { exact: true }).click();
  await page1.getByText('1522350').click();
  await page1.getByRole('button', { name: 'Place Order ' }).click();
  await page1.goto('https://staging.spidercubed-staging.co.uk/Orders/Details/1522350');
  await page1.getByText('Turner User, Turner and Turner', { exact: true }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.locator('div').filter({ hasText: 'Home New Order New Order CLS Insurance My Legal Indemnity View Orders Accounting' }).nth(1).click();
  const page2 = await page2Promise;
  await page1.getByText('Turner User, Turner and Turner', { exact: true }).click();
  await page1.getByRole('link', { name: 'Log Out ' }).click();
  await page1.getByLabel('Username').click();
  await page1.getByLabel('Username').fill('rkarlapudicore');
  await page1.getByLabel('Password').click();
  await page1.getByLabel('Password').click();
  await page1.getByLabel('Password').fill('DND@2023');
  await page1.getByRole('button', { name: 'Log On' }).click();
  await page1.getByText('View Orders').first().click();
  await page1.getByRole('link', { name: 'View Orders' }).click();
  await page.getByText('Case Number: 758281').click();
  await page.getByText('Case Number: 758281').click();
  await page1.getByPlaceholder('Case Number, Postcode, Street Name').click();
  await page1.getByPlaceholder('Case Number, Postcode, Street Name').fill('758281');
  await page1.getByRole('button', { name: ' SEARCH' }).click();
  await page1.getByText('1522350').click();
  await page1.getByRole('button', { name: 'Process Order ' }).click();
  await page1.getByRole('button', { name: 'Pay By BACS ' }).click();
  await page1.getByRole('button', { name: 'Confirm ' }).click();
  await page1.goto('https://staging.spidercubed-staging.co.uk/Orders/Details/1522350');
  await page1.getByRole('button', { name: 'Funds Received ' }).click();
  await page1.goto('https://staging.spidercubed-staging.co.uk/Orders/Details/1522350');
  await page.getByRole('button', { name: 'Case History Open ' }).click();
  await page.getByText('Date17/04/2023 13:48 EventPurchase Service quoted StatusOpen UserTurner User').click();
});