import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.brighterlawsuite-staging.co.uk/Account/LogOn');
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('TurnerUser');
  await page.getByLabel('Username').press('Tab');
  await page.getByLabel('Password').fill('Test1234');
  await page.getByRole('button', { name: 'Log On' }).click();
  await page.getByRole('link', { name: ' Add New Client' }).click();
  await page.locator('a').filter({ hasText: 'Select Team' }).click();
  await page.locator('#introducerTeamId_chosen').getByRole('textbox').fill('li');
  await page.locator('#introducerTeamId_chosen').getByText('Lindsey Williams').click();
  await page.getByText('Purchase', { exact: true }).first().click();
  await page.getByLabel('Purchase Postcode').click();
  await page.getByLabel('Purchase Postcode').fill('rg303ng');
  await page.getByText('Find Local Authority').click();
  await page.getByLabel('Purchase Price').click();
  await page.getByLabel('Purchase Price').fill('100');
  await page.locator('a').filter({ hasText: 'Select Title' }).click();
  await page.locator('#titleId_chosen').getByText('Mrs', { exact: true }).click();
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('rathna');
  await page.getByLabel('Last Name').click();
  await page.getByLabel('Last Name').fill('karlapudi');
  await page.getByLabel('Email Address').click();
  await page.getByLabel('Email Address').fill('rathnamani.karlapudi@dyedurham.com');
  await page.getByLabel('Phone Number').click();
  await page.getByLabel('Phone Number').fill('1234567890');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#details div').filter({ hasText: 'Client Details Service Address Line 1 is required. Company Title MrMrsMissMsMxMr' }).getByPlaceholder('Start typing a postcode or address').click();
  await page.locator('#details div').filter({ hasText: 'Client Details Service Address Line 1 is required. Company Title MrMrsMissMsMxMr' }).getByPlaceholder('Start typing a postcode or address').fill('rg303ng');
  await page.getByText('1 Ainsdale Crescent Reading, RG30 3NG', { exact: true }).click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(1).click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(1).fill('rg303ng');
  await page.getByText('1 Ainsdale Crescent Reading, RG30 3NG', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).first().click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('button', { name: 'Order ' }).click();
  const page1 = await page1Promise;
  await page1.locator('a').filter({ hasText: 'SELECT COMPANY' }).click();
  await page1.locator('#companySelect_chosen').getByText('Turner and Turner').click();
  await page1.locator('#branches_chosen a').click();
  await page1.locator('#branches_chosen').getByRole('textbox').fill('y');
  await page1.locator('#branches_chosen').getByText('Yorkminster').click();
  await page1.locator('a').filter({ hasText: 'Select an Option' }).click();
  await page1.locator('#teams_chosen').getByRole('textbox').fill('l');
  await page1.locator('#teams_chosen').getByText('Lindsey Williams').click();
  await page1.getByRole('button', { name: 'Next' }).click();
  await page1.getByRole('button', { name: '1 Ainsdale Crescent, READING, Berkshire, RG30 3NG', exact: true }).click();
  await page1.getByRole('button', { name: 'Next ' }).click();
  await page1.locator('div:nth-child(2) > .product > .clearfix > a:nth-child(2)').first().click();
  await page1.getByText('Proceed With Order').click();
  await page1.getByText('Funds To Collect').click();
  await page1.locator('#customer_firstname').click();
});