import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging.spidercubed-staging.co.uk/account/logon?ReturnUrl=%2f');
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('TurnerUser');
  await page.getByLabel('Username').press('Tab');
  await page.getByLabel('Password').fill('Test1234');
  await page.getByLabel('Password').press('Enter');
  await page.locator('div:nth-child(4) > .link-box > .btn').click();
  await page.locator('a').filter({ hasText: 'SELECT COMPANY' }).click();
  await page.locator('#companySelect_chosen').getByText('Turner and Turner').click();
  await page.locator('#branches_chosen a').click();
  await page.locator('#branches_chosen').getByText('Yorkminster').click();
  await page.locator('a').filter({ hasText: 'Select an Option' }).click();
  await page.locator('#teams_chosen').getByRole('textbox').fill('lin');
  await page.locator('#teams_chosen').getByText('Lindsey Williams').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'New Order' }).click();
  await page.getByPlaceholder('Start Typing...').click();
  await page.getByPlaceholder('Start Typing...').fill('TW7 4SY');
  await page.getByRole('button', { name: '1 Honnor Gardens, ISLEWORTH, Middlesex, TW7 4SY' }).click();
  await page.locator('#reference').click();
  await page.locator('#reference').fill('123');
  await page.locator('#Hmlr_question_').nth(2).click();
  await page.locator('#Hmlr_question_').nth(2).fill('GUser001');
  await page.locator('#Hmlr_question_').nth(3).click();
  await page.locator('#Hmlr_question_').nth(3).fill('landreg001');
  await page.getByRole('button', { name: 'Save and Continue' }).click();
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.locator('a').filter({ hasText: 'Select an Option' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Document Registration' }).click();
  await page.locator('#applicationType_chosen').getByRole('textbox').click();
  await page.locator('#applicationType_chosen').getByText('Charge', { exact: true }).click();
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.locator('#DocumentUpload_Mandatory_4401637').click();
  await page.locator('#DocumentUpload_Mandatory_4401637').setInputFiles('Capture.JPG');
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.getByPlaceholder('Enter Value').click();
  await page.getByPlaceholder('Enter Value').fill('30000');
  await page.getByRole('button', { name: '' }).click();
  await page.getByText('Fees Charge Fee(£) *This fee was manually edited Value(£) *This fee was manually').click();
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.locator('div:nth-child(3) > label > .custom-toggle').click();
  await page.getByRole('button', { name: 'Place Order ' }).click();
  await page.getByText('CopyType is mandatory for Charge').click();
});