import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://staging.spidercubed-staging.co.uk/account/logon?ReturnUrl=%2f');
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('TurnerUser');
  await page.getByLabel('Username').press('Tab');
  await page.getByLabel('Password').fill('Test1234');
  await page.getByLabel('Password').press('Enter');
  await page.getByText('DRS').click();
  await page.locator('div:nth-child(4) > .link-box > .btn').click();
  await page.locator('a').filter({ hasText: 'SELECT COMPANY' }).click();
  await page.locator('#companySelect_chosen').getByText('Turner and Turner').click();
  await page.locator('#branches_chosen a').click();
  await page.locator('#branches_chosen').getByText('Yorkminster').click();
  await page.locator('a').filter({ hasText: 'Select an Option' }).click();
  await page.locator('#teams_chosen').getByRole('textbox').fill('li');
  await page.locator('#teams_chosen').getByText('Lindsey Williams').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'New Order' }).click();
  await page.getByPlaceholder('Start Typing...').click();
  await page.getByPlaceholder('Start Typing...').fill('TW7 4SY');
  await page.getByRole('button', { name: '1 Honnor Gardens, ISLEWORTH, Middlesex, TW7 4SY' }).click();
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.getByRole('button', { name: ' Add Party' }).click();
  await page.locator('a').filter({ hasText: 'Select the party type' }).click();
  await page.locator('#partytype_chosen').getByText('Individual').click();
  await page.locator('a').filter({ hasText: 'Select the representation type' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Represented by lodging conveyancer' }).click();
  await page.locator('label').filter({ hasText: 'Is Applicant' }).locator('span').nth(1).click();
  await page.getByRole('textbox').nth(2).click();
  await page.locator('party div').filter({ hasText: 'Forenames *' }).nth(2).click();
  await page.getByRole('textbox').nth(2).fill('Forename');
  await page.getByRole('textbox').nth(2).press('Tab');
  await page.getByRole('textbox').nth(3).fill('Surname');
  await page.getByRole('textbox').nth(3).press('Tab');
  await page.locator('a').filter({ hasText: 'Select the Address For Service Type' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Current' }).click();
  await page.getByRole('button', { name: ' Add Role' }).click();
  await page.locator('a').filter({ hasText: 'Select the application' }).click();
  await page.getByRole('listitem').filter({ hasText: /^Charge$/ }).click();
  await page.locator('a').filter({ hasText: 'Select the role type' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Lender' }).click();
  await page.locator('.tabbed-content-block-subsection > div:nth-child(4) > div > .form-control').first().click();
  await page.locator('.tabbed-content-block-subsection > div:nth-child(4) > div > .form-control').first().fill('1525244');
  await page.locator('input[type="date"]').fill('2023-05-17');
  await page.getByRole('button', { name: ' Add Party' }).click();
  await page.locator('a').filter({ hasText: 'Select the party type' }).click();
  await page.getByText('Individual').nth(4).click();
  await page.locator('a').filter({ hasText: 'Select the representation type' }).click();
  await page.getByText('Represented by lodging conveyancer').nth(4).click();
  await page.locator('div:nth-child(5) > div > .animated > .tabbed-content-block-panel > div > div:nth-child(2) > label > .checkmark').first().click();
  await page.locator('div:nth-child(5) > div > .animated > .tabbed-content-block-panel > div > div:nth-child(2) > label > .checkmark').first().click();
  await page.locator('div:nth-child(5) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div > .form-control').first().click();
  await page.locator('div:nth-child(5) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div > .form-control').first().fill('Forename');
  await page.locator('div:nth-child(5) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div > .form-control').first().press('Tab');
  await page.locator('div:nth-child(5) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div:nth-child(2) > .form-control').fill('Surname');
  await page.locator('div:nth-child(5) > div > .animated > .tabbed-content-block-panel > div > div:nth-child(2) > label > .checkmark').first().click();
  await page.locator('a').filter({ hasText: 'Select the Address For Service Type' }).click();
  await page.getByText('Current').nth(4).click();
  await page.getByRole('button', { name: ' Add Role' }).nth(1).click();
  await page.locator('a').filter({ hasText: 'Select the application' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Charge' }).nth(2).click();
  await page.locator('a').filter({ hasText: 'Select the role type' }).click();
  await page.getByText('Borrower').nth(3).click();
  await page.getByText('Borrower').nth(3).click();
  await page.locator('form[name="mainForm"] div').filter({ hasText: 'Representatives Lodging Conveyancer The lodging conveyancer for this DRS submiss' }).nth(3).click();
  await page.locator('#assets > div:nth-child(3)').click();
  await page.getByRole('button', { name: ' Add Party' }).click();
  await page.locator('a').filter({ hasText: 'Select the party type' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Individual' }).nth(2).click();
  await page.locator('a').filter({ hasText: 'Select the representation type' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Represented by lodging conveyancer' }).nth(2).click();
  await page.locator('div:nth-child(7) > div > .animated > .tabbed-content-block-panel > div > div:nth-child(2) > label > .checkmark').first().click();
  await page.locator('div:nth-child(7) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div > .form-control').first().click();
  await page.locator('div:nth-child(7) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div > .form-control').first().fill('forename');
  await page.locator('div:nth-child(7) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div > .form-control').first().press('Tab');
  await page.locator('div:nth-child(7) > div > .animated > .tabbed-content-block-panel > div:nth-child(2) > div:nth-child(2) > .form-control').fill('Surname');
  await page.locator('a').filter({ hasText: 'Select the Address For Service Type' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Current' }).nth(2).click();
  await page.getByRole('button', { name: ' Add Role' }).nth(2).click();
  await page.locator('a').filter({ hasText: 'Select the application' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Discharge' }).nth(2).click();
  await page.locator('a').filter({ hasText: 'Select the role type' }).click();
  await page.locator('.tabbed-content-left').click();
  await page.locator('a').filter({ hasText: 'Select the role type' }).click();
  await page.getByRole('button', { name: ' Remove Role' }).nth(2).click();
  await page.getByRole('button', { name: ' Continue' }).click();
  await page.getByRole('button', { name: ' Add Document' }).click();
  await page.getByText('Representation and Parties').click();
  await page.getByRole('button', { name: '' }).nth(4).click();
  await page.getByRole('button', { name: ' Continue' }).click();
});