import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.brighterlawsuite-staging.co.uk/Account/LogOn');
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('DextersAutoTestUser');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Test1234');
  await page.getByRole('button', { name: 'Log On' }).click();
  await page.getByRole('heading', { name: ' Track Active Cases' }).click();
  await page.locator('a').filter({ hasText: /^Active Case$/ }).click();
  await page.getByRole('listitem').filter({ hasText: /^Open$/ }).click();
  await page.getByRole('row', { name: '758034 Mar 8, 2023 Lname080323 192 Oxford Road, RG3... Sale David Burrell (Turner and Turner, Yorkminster) Automation Test Dexter Williams (Dexters, Hammersmith) Mar 8, 2023 Active Case' }).getByRole('cell', { name: '758034' }).click();
  await page.getByRole('tab', { name: 'Transaction Details' }).click();
  await page.getByText('Edit Fees').first().click();
  await page.locator('.box > .form-group > input').first().click();
  await page.locator('.row > div:nth-child(2) > .box').first().click();
  await page.locator('.box > .form-group > input').first().click();
  await page.locator('.box > .form-group > input').first().fill('200');
  await page.getByRole('button', { name: 'Recalculate Fees' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Recalculate All' }).locator('a').click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).fill('test');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'Yes, communicate' }).click();
  await page.getByRole('button', { name: 'Next' }).first().click();
  await page.getByRole('tab', { name: 'Transaction Details' }).click();
  await page.getByText('Edit Fees').nth(1).click();
  await page.locator('div:nth-child(2) > div > .col-md-8 > div:nth-child(5) > div > div > div:nth-child(2) > .box > .form-group > input').click();
  await page.locator('div:nth-child(2) > div > .col-md-8 > div:nth-child(5) > div > div > div:nth-child(2) > .box > .form-group > input').click();
  await page.locator('div:nth-child(2) > div > .col-md-8 > div:nth-child(5) > div > div > div:nth-child(2) > .box > .form-group > input').fill('100');
  await page.locator('div:nth-child(2) > div > .col-md-8 > div:nth-child(5) > div > div').click();
  await page.getByRole('button', { name: 'Recalculate Fees' }).click();
  await page.getByRole('button', { name: 'Recalculate Fees' }).click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).fill('test');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Recalculate Fees' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Recalculate All' }).locator('a').click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).fill('test');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByRole('button', { name: 'Yes, communicate' }).click();
  await page.getByRole('button', { name: 'Next' }).first().click();
});