import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.brighterlawsuite-staging.co.uk/Account/LogOn');
  await page.getByLabel('Username').dblclick();
  await page.getByLabel('Username').fill('DextersAutoTestUser');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Test1234');
  await page.getByRole('button', { name: 'Log On' }).click();
  await page.getByRole('link', { name: ' Add New Client' }).click();
  await page.locator('a').filter({ hasText: 'Select Team' }).click();
  await page.locator('#introducerTeamId_chosen').getByText('Dexter Williams').click();
  await page.getByRole('radio', { name: 'Sale & Purchase' }).check();
  await page.getByLabel('Sale Price').click();
  await page.getByLabel('Sale Price').fill('100');
  await page.getByLabel('Purchase Postcode').click();
  await page.getByLabel('Purchase Postcode').fill('RG30 3NG');
  await page.getByText('Find Local Authority').click();
  await page.getByLabel('Purchase Price').click();
  await page.getByLabel('Purchase Price').click();
  await page.getByLabel('Purchase Price').fill('200');
  await page.getByLabel('First Name').click();
  await page.getByLabel('First Name').fill('Rathna');
  await page.getByLabel('First Name').press('Tab');
  await page.getByLabel('Last Name').fill('Karlapudi');
  await page.getByLabel('Last Name').press('Tab');
  await page.getByLabel('Email Address').fill('rathnamani.karlapudi@dyedurham.com');
  await page.getByLabel('Phone Number').click();
  await page.getByLabel('Phone Number').fill('441234567899');
  await page.getByRole('button', { name: 'Next' }).click();

  await page.locator('form').filter({ hasText: 'Sale Fees, based on property price of £100 and an NPV of £ Legal Fees Net LegalS' }).getByTitle('Modify Fees').click();
    await page.getByRole('textbox', { name: '0' }).click();
    await page.getByRole('textbox', { name: '0' }).fill('100');
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).fill('test');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.locator('form').filter({ hasText: 'Purchase Fees, based on property price of £200 and an NPV of £ Legal Fees Net Le' }).getByTitle('Modify Fees').click();
  await page.getByRole('cell', { name: ' Add Fee Or Discount' }).nth(1).click();
  await page.getByRole('row', { name: 'Fee Name (Required) 0', exact: true }).getByPlaceholder('0').click();
  await page.getByRole('row', { name: 'Fee Name (Required) 0', exact: true }).getByPlaceholder('0').fill('200');
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).click();
  await page.getByRole('textbox', { name: 'Please enter the reason for amending this quote here.' }).fill('test');
  await page.locator('.col-md-8 > div:nth-child(3) > div').click();
  await page.locator('.col-md-8 > div:nth-child(3) > div').click();
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.locator('form').filter({ hasText: 'Purchase Fees, based on of £200 and an NPV of £ Legal Fees Net LegalServiceFee £' }).getByRole('button', { name: 'Next' }).click();
  await page.locator('#details div').filter({ hasText: 'Client Details Title is required. Service Address Line 1 is required. Company Ti' }).getByPlaceholder('Start typing a postcode or address').click();
  await page.locator('#details div').filter({ hasText: 'Client Details Title is required. Service Address Line 1 is required. Company Ti' }).getByPlaceholder('Start typing a postcode or address').click();
  await page.locator('#details div').filter({ hasText: 'Client Details Title is required. Service Address Line 1 is required. Company Ti' }).getByPlaceholder('Start typing a postcode or address').fill('RG3');
  await page.getByText('R G 3 Suspension UK, Unit B11, Great Knollys Street Reading, RG1 7HN').click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(2).click();
  await page.getByPlaceholder('Start typing a postcode or address').nth(2).fill('RG1');
  await page.getByText('RG10 0AA Waltham Road, Reading').click();
  await page.getByText('7 Highfield Court, Waltham Road Twyford, Reading, RG10 0AA', { exact: true }).click();
  await page.getByRole('button', { name: 'Next' }).click();
});